name: Update NSE Scanner

on:
  schedule:
    - cron: '45 14 * * 1-5'

  workflow_dispatch:

jobs:
  update-sheet:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Create Credentials File
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run Python Script
        run: python update_sheet.py
